<?php
/**
 * @author Florent HAZARD <f.hazard@sowapps.com>
 */

use Symfony\Component\Config\Definition\Configurator\DefinitionConfigurator;

return static function (DefinitionConfigurator $definition): void {
	// SoCore Configuration Specifications
	// TODO Add forms ? (like user registration)
	// @formatter:off
    $definition->rootNode()
        ->children()

->arrayNode('app')
	->addDefaultsIfNotSet()
	->children()
		->scalarNode('label_tk')->defaultValue('app.label')->end()
	->end()
->end()
->arrayNode('routing')
	->addDefaultsIfNotSet()
	->children()
		->arrayNode('route')
			->addDefaultsIfNotSet()
			->children()
				->scalarNode('public_default')->defaultValue('home')->end()
				->scalarNode('admin_default')->defaultValue('so_core_admin_index')->end()
			->end()
		->end()
	->end()
->end()
->arrayNode('user')
	->addDefaultsIfNotSet()
	->children()
		->scalarNode('class')->defaultValue('\App\Entity\User')->end()
		->arrayNode('activation')
		    ->addDefaultsIfNotSet()
			->children()
				->scalarNode('expire')
			        ->defaultValue("24 hours")
				->end()
			->end()
		->end()
		->arrayNode('recover')
		    ->addDefaultsIfNotSet()
			->children()
				->scalarNode('expire')
					->defaultValue("24 hours")
				->end()
			->end()
		->end()
		->arrayNode('apiToken')
		    ->addDefaultsIfNotSet()
			->children()
				->scalarNode('expire')->defaultValue("24 hours")->end()
				->scalarNode('limit')->defaultValue(3)->end()
			->end()
		->end()
	->end()
->end()
->arrayNode('admin')
	->addDefaultsIfNotSet()
	->children()
		->arrayNode('auth')
			->children()
				->arrayNode('background')->scalarPrototype()->end()->end()
			->end()
		->end()
	->end()
->end()
->arrayNode('email')
	->addDefaultsIfNotSet()
	->children()
		->arrayNode('from')
			->children()
				->scalarNode('name')->end()
				->scalarNode('email')->end()
			->end()
		->end()
		->arrayNode('contact')
			->children()
				->scalarNode('name')->end()
				->scalarNode('email')->end()
			->end()
		->end()
		->arrayNode('online_view')
			->children()
				->scalarNode('expire')
        			->defaultValue("72 hours")
			    ->end()
			->end()
		->end()
	->end()
->end()
->arrayNode('file')
	->addDefaultsIfNotSet()
	->children()
		->scalarNode('store_path')->defaultValue('%kernel.project_dir%/var/store/files')->end()
		->scalarNode('public_path')->defaultValue('%kernel.project_dir%/public')->end()
		->arrayNode('purposes')
			->prototype('scalar')->end()
			->defaultValue([])
		->end()
		->arrayNode('sources')
			->prototype('scalar')->end()
			->defaultValue(['http_upload', 'local'])
		->end()
		->arrayNode('storages')
			->prototype('scalar')->end()
			->defaultValue(['local'])
		->end()
	->end()
->end()

    ->end();
    // @formatter:on
};
